- name: List floating ips
  hcloud_floating_ip:
    state: list
  register: list_ips
- name: Reset ip_exists
  set_fact:
    ip_exists: false
- name: Check if ip already exists
  set_fact:
    ip_exists: true
  when: "item.description == ip_description"
  loop: "{{ list_ips.floating_ips|list }}"
  ignore_errors: true
- name: Create floating ip
  hcloud_floating_ip:
    state: present
    home_location: "{{ location }}"
    type: ipv4
    description: "{{ ip_description }}"
  register: "{{ register_variable }}"
  when: "not ip_exists"
- debug:
    msg: "Ip already exists, not creating"
  when: "ip_exists"
- name: List floating ips afterwards
  hcloud_floating_ip:
    state: list
  register: list_ips_after
- name: register created floating ip
  set_fact: { "{{ register_variable }}":"{{ item }}" }
  when: "item.description == ip_description"
  loop: "{{ list_ips_after.floating_ips|list }}"
