defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":{{ http_port }}"
	  [entryPoints.http.redirect]
		 entryPoint = "https"
  [entryPoints.https]
  address = ":{{ https_port }}"
    [entryPoints.https.tls]
{% for item in extra_ports %}
  [entryPoints.{{ item.name}}]
  address = ":{{ item.port }}"
	{% if item.tls is defined %}
    [entryPoints.{{ item.name }}.tls]
	{% endif %}
{% endfor %}

logLevel = "INFO"

[traefikLog]

[accessLog]

[respondingTimeouts]
readTimeout = "0s"
writeTimeout = "0s"
idleTimeout = "1200s"

[acme]
email = "{{ email }}"

storage = "/etc/traefik/acme.json"

entryPoint = "https"

[[acme.domains]]
   main = "{{ url }}"

{% if challenge == "dns" %}
[acme.dnsChallenge]
	provider = "{{ dns_provider }}"

{% else %}
[acme.httpChallenge]
  entryPoint = "http"
{% endif %}

[file]
# Backends
[backends]

  [backends.rancher]
    [backends.rancher.healthcheck]
	 	path = "/ping"
		interval = "5s"
    [backends.rancher.circuitbreaker]
		 expression = "NetworkErrorRatio() > 0.5"
    [backends.rancher.servers]
{% for host in groups[group] %}
      [backends.rancher.servers.server{{ loop.index0 }}]
	{% if host != inventory_hostname %}
        url = "http://{{ hostvars[host].ansible_default_ipv4.address }}:8080"
	{% else %}
	{# Der Port 8080 ist auf die Host-Ip gebunden. Zugriff vom eigenen Host #}
	{# passiert aber immer über localhost. #}
	{# Lösung: Zugriff über das geteilte Docker Netzwerk #}
        url = "http://rancher-server:8080"
	{% endif %}
{% endfor %}

# Frontends
[frontends]

  [frontends.frontend1]
    entryPoints = ["http", "https"]
    backend = "rancher"
    passHostHeader = true

    [frontends.frontend1.routes]
      [frontends.frontend1.routes.route0]
        rule = "Host:{{ url }}"
