---
- name: Create temporary file for install python script
  tempfile:
    prefix: install
    state: file
  register: tempfile
  when: 'ansible_hostname == "rescue"'
- name: Install if system is in rescue mode
  shell: "/root/.oldroot/nfs/install/installimage -a -n {{ inventory_hostname }} -b grub -r no -p /boot:ext4:256M,lvm:vg0:all -v {% for item in volumes %}{%- if not loop.first -%},{%- endif -%}vg0:{{ item.name }}:{{ item.mountpoint }}:{{ item.fs }}:{{ item.size }}{%- endfor %} -d sda -t yes -i /root/.oldroot/nfs/install/../images/Debian-9?-stretch-64-minimal.tar.gz"
  when: 'ansible_hostname == "rescue"'
- name: mount root
  mount:
    src: "/dev/mapper/vg0-{{ root }}"
    path: /target
    fstype: "{{ root_type }}"
    state: mounted
  when: 'ansible_hostname == "rescue"'
- name: mount dev into root
  mount:
    src: /dev
    path: /target/dev
    opts: bind
    fstype: none
    state: mounted
  when: 'ansible_hostname == "rescue"'
- name: mount proc into root
  mount:
    src: /proc
    path: /target/proc
    opts: bind
    fstype: none
    state: mounted
  when: 'ansible_hostname == "rescue"'
- name: update apt in /target
  command: chroot /target apt-get update
  when: 'ansible_hostname == "rescue"'
- name: install python in /target
  command: chroot /target apt-get -y install python
  when: 'ansible_hostname == "rescue"'
- name: unmount dev in root
  mount:
    path: /target/dev
    state: unmounted
  when: 'ansible_hostname == "rescue"'
- name: unmount proc in root
  mount:
    path: /target/proc
    state: unmounted
  when: 'ansible_hostname == "rescue"'
- name: unmount root
  mount:
    src: "/dev/mapper/vg0-{{ root }}"
    path: /target
    state: unmounted
  when: 'ansible_hostname == "rescue"'
- name: Reboot system
  command: "shutdown -r 1"
  when: 'ansible_hostname == "rescue"'
- name: Wait for system to come back online
  local_action: "wait_for host={{ ansible_ssh_host }} state=started delay=90 timeout=60"
  when: 'ansible_hostname == "rescue"'
