---
- name: python3-lxml
  apt: 
    name: python3-lxml
    state: present
  tags: ['cluster', 'stonith', 'hetzner']
- name: python3-pip
  apt: 
    name: python3-pip
    state: present
  tags: ['cluster', 'stonith', 'hetzner']
- name:
  pip:
    executable: pip3
    name: hetznercloud
    state: present
  tags: ['cluster', 'stonith', 'hetzner']
- name: Install Hetzner Cloud STONITH resource
  copy: 
    src: hetzner_cloud
    dest: /usr/lib/stonith/plugins/external/
    mode: 0755
  tags: ['cluster', 'stonith', 'hetzner']
- name: Create STONITH devies
  # TODO: use or simulate serial: 1 for this task. It works fine when creating,
  # but breaks when changing an existing stonith resource
  pcs_resource:
    name: "STONITH_{{ ansible_hostname }}"
    state: present
    resource_type: "stonith:external/hetzner_cloud"
    options: "api_token={{ api_token }} meta failure-timeout=10"
  tags: ['cluster', 'stonith', 'hetzner']
- name: Force stonith location not on own host
  pcs_constraint_location:
    state: present
    resource: "STONITH_{{ ansible_hostname }}"
    node_name: "{{ ansible_hostname  }}"
    score: "-INFINITY"
  tags: ['cluster', 'stonith', 'hetzner']
