# all tools which are necessary to for basic installation and user creation
---
- name: Install base tools
  apt:
    name:
    - zsh
    - sudo
    - rsync
    - git
    - lvm2
    - tzdata
    state: latest
  tags: ['apt', 'base']
- name: Set Timzeone
  timezone:
    name: "{{ timezone }}"
  tags: ['timezone', 'base']
