mysql_port: 3306
data_path: /var/lib/mysql
bind_address: "{{ ansible_default_ipv4 }}"
max_connections: 150
wait_timeout: 600
interactive_timeout: 1200
innodb_buffer_pool_size: 1073741824 #1GB
innodb_flush_log_at_trx_commit: 2
query_cache_limit: '1M'
query_cache_size: '16M'
join_buffer_size: 262144
skip_name_resolve: true
version: distribution
default_domain: ftp.hosteurope.de
versions:
  stretch:
    "10.1":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.1/debian
      domain: ftp.hosteurope.de
      version: 10.1.*
      key:
        server: keyserver.ubuntu.com
        name: "0xF1656F24C74CD1D8"
    "10.2":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.2/debian
      domain: ftp.hosteurope.de
      version: 10.2.*
      key:
        server: keyserver.ubuntu.com
        name: "0xF1656F24C74CD1D8"
    "10.3":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.3/debian
      domain: ftp.hosteurope.de
      version: 1:10.3.*
      key:
        server: keyserver.ubuntu.com
        name: "0xF1656F24C74CD1D8"
  jessie:
    "10.1":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.1/debian
      domain: ftp.hosteurope.de
      key:
        server: keyserver.ubuntu.com
        name: "0xcbcb082a1bb943db"
    "10.2":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.2/debian
      domain: ftp.hosteurope.de
      key:
        server: keyserver.ubuntu.com
        name: "0xcbcb082a1bb943db"
    "10.3":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.3/debian
      domain: ftp.hosteurope.de
      key:
        server: keyserver.ubuntu.com
        name: "0xcbcb082a1bb943db"
  xenial:
    "10.1":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.1/ubuntu
      domain: ftp.hosteurope.de
      key:
        server: hkp://keyserver.ubuntu.com:80
        name: "0xF1656F24C74CD1D8"
    "10.2":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.2/ubuntu
      domain: ftp.hosteurope.de
      key:
        server: hkp://keyserver.ubuntu.com:80
        name: "0xF1656F24C74CD1D8"
    "10.3":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.3/ubuntu
      domain: ftp.hosteurope.de
      key:
        server: hkp://keyserver.ubuntu.com:80
        name: "0xF1656F24C74CD1D8"
  bionic:
    "10.1":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.1/ubuntu
      domain: ftp.hosteurope.de
      key:
        server: hkp://keyserver.ubuntu.com:80
        name: "0xF1656F24C74CD1D8"
    "10.2":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.2/ubuntu
      domain: ftp.hosteurope.de
      key:
        server: hkp://keyserver.ubuntu.com:80
        name: "0xF1656F24C74CD1D8"
    "10.3":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.3/ubuntu
      domain: ftp.hosteurope.de
      key:
        server: hkp://keyserver.ubuntu.com:80
        name: "0xF1656F24C74CD1D8"
  cosmic:
    "10.2":
      repo: http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.2/ubuntu
      domain: ftp.hosteurope.de
      arches: amd64
      key:
        server: hkp://keyserver.ubuntu.com:80
        name: "0xF1656F24C74CD1D8"
