mysql_port: 3306
data_path: /var/lib/mysql
bind_address: "{{ ansible_default_ipv4 }}"
max_connections: 150
wait_timeout: 600
interactive_timeout: 1200
innodb_buffer_pool_size: 1073741824 #1GB
innodb_flush_log_at_trx_commit: 2