---
- name: copy etcd
  copy:
    src: etcd
    dest: /usr/local/bin/etcd
    mode: 0755
  tags: ['etcd']
- name: copy etcdctl
  copy:
    src: etcdctl
    dest: /usr/local/bin/etcdctl
    mode: 0755
  tags: ['etcd']
- name: Create /var/lib/etcd
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0755
  tags: ['etcd']
- name: copy etcd.service
  template:
    src: etcd.service
    dest: /etc/systemd/system/etcd.service
    mode: 0644
  tags: ['etcd']
- name: enable etcd.service
  systemd:
    name: etcd
    enabled: true
  tags: ['etcd']
- name: start etcd.service
  systemd:
    name: etcd
    state: started
  tags: ['etcd']
