---
- name: Install Tools
  apt:
    name: "{{ item }}"
    state: latest
  tags: [ 'tools' ]
  with_items:
  - screen
  - vim
  - git
  - unattended-upgrades
  - apt-listchanges
- name: Copy unattended-upgrades config
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
  tags: [ 'tools', 'updates' ]
