---
- name: Install Tools
  apt:
    name: 
    - screen
    - vim
    - git
    - unattended-upgrades
    - apt-listchanges
    - logrotate
    - fail2ban
    state: latest
  tags: [ 'tools' ]
- name: Copy unattended-upgrades config
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
  tags: [ 'tools', 'updates' ]
- name: Copy logrotate cron file to /etc/cron.hourly
  template:
    src: logrotate
    dest: /etc/cron.hourly/logrotate
    mode: 0644
  tags: [ 'tools', 'updates' ]
- name: Copy logrotate rsyslog config
  template:
    src: rsyslog
    dest: /etc/logrotate.d/rsyslog
    mode: 0644
  tags: [ 'tools', 'updates' ]
- name: Create reboot
  cron:
    state: present
    user: root
    cron_file: 'update_auto_reboot'
    disabled: "{{ not auto_restart }}"
    job: "test -f /var/run/reboot-required && /sbin/shutdown -r now"
    hour: "{{ restart.hour }}"
    minute: "{{ restart.minute }}"
    weekday: "{{ ansible_play_batch.index(inventory_hostname) + 1 % 7 }}"
  tags: [ 'tools', 'updates' ]


