- name: sysctl settings
  sysctl:
    state: present
    sysctl_file: /etc/sysctl.d/50-network.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: net.core.rmem_max
      value: 134217728
    - name: net.core.wmem_max
      value: 134217728
    - name: net.core.wmem_max
      value: 134217728
    - name: net.ipv4.tcp_rmem
      value: 4096 87380 67108864
    - name: net.ipv4.tcp_wmem
      value: 4096 87380 67108864
