#!/bin/sh

source /etc/default/nfs-kernel-server

if [ -n "${LEASE_TIMEOUT}" ] ; then
  echo ${LEASE_TIMEOUT} > /proc/fs/nfsd/nfsv4leasetime
fi
if [ -n "${GRACE_TIMEOUT}" ] ; then
  echo ${GRACE_TIMEOUT} > /proc/fs/nfsd/nfsv4gracetime
fi
