---
- name: Install kernel nfs server
  apt:
    name:
      - nfs-kernel-server
      - quota
    state: present
  tags: ['nfs-server']
- name: Set nfsdargs grace-time and lease-time
  lineinfile:
    regexp: 'RPCNFSDOPTS=.*'
    path: /etc/default/nfs-kernel-server
    line: 'RPCNFSDOPTS="--grace-time {{ grace_timeout }} --lease-time {{ lease_timeout }}"'
  tags: ['nfs-server', 'nfs-server-grace']
- name: Set nfs thread count
  lineinfile:
    regexp: 'RPCNFSDCOUNT=.*'
    path: /etc/default/nfs-kernel-server
    line: 'RPCNFSDCOUNT="{{ threads }}"'
  tags: ['nfs-server', 'nfs-server-grace']
- name: upload /etc/exports
  template:
    src: exports
    dest: /etc/exports
  notify:
    - Reload exports
  tags: ['nfs-server']
- name: Check if export is mounted
  shell: "mount | grep -q {{ item.mount }}"
  ignore_errors: true
  with_items: "{{ exports }}"
  changed_when: false
  register: mounted
  tags: ['nfs-server']
- name: Create export directory
  file:
    path: "{{ item.item.path }}"
    state: directory
    mode: 0777
  when: "item.rc == 0"
  with_items: "{{ mounted.results }}"
  tags: ['nfs-server']
- name: Create info directory
  file:
    path: "{{ item.item.mount }}/nfsinfo"
    state: directory
  when: "item.rc == 0"
  with_items: "{{ mounted.results }}"
  tags: ['nfs-server']
- name: Disable rpc-statd - File locking für nfs
  systemd:
    name: rpc-statd
    enabled: false
  tags: ['nfs-server']
