---
- name: "Build hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*\s{{ item }}.*'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}} {{ hostvars[item].ansible_hostname }}"
    state: present
  when: ( hostvars[item].ansible_default_ipv4 is defined ) and ( hostvars[item].ansible_default_ipv4.address is defined )
  with_items: "{{ groups[hostgroup] }}"
